items:
  - name: convenejudgement
    kind: tool
    category: recon
    desc: Recon framework
    tags:
      - recon
    action: use convenejudgement
  - name: mistyrelay
    kind: tool
    category: modeling
    desc: Modeling framework
    tags:
      - modeling
    action: use mistyrelay
  - name: piercingeye
    kind: tool
    category: osint
    desc: Osint framework
    tags:
      - osint
    action: use piercingeye
  - name: happybond
    kind: tool
    category: post
    desc: Post-exploitation framework
    tags:
      - post
      - post-exploitation
    action: use happybond
  - name: shallowdawn
    kind: tool
    category: reverse shell
    desc: Reverse shell framework
    tags:
      - reverse
      - shell
      - reverseshell
    action: use shallowdawn
  - name: spiffyspark
    kind: tool
    category: analysis
    desc: Analysis framework
    tags:
      - analysis
    action: use spiffyspark
  - name: goldenbullet
    kind: tool
    category: exploitation
    desc: Non-Windows Exploitation Techniques
    tags:
      - general
      - exploitation
    action: use goldenbullet
  - name: crazyingrate
    kind: tool
    category: exploitation
    desc: Linux exploitation framework
    tags:
      - linux
      - exploitation
    action: use crazyingrate
  - name: coldheart
    kind: tool
    category: exploitation
    desc: Windows SMB Exploitation Techniques
    tags:
      - microsoft
      - windows
      - exploit
      - expploitation
      - smb
    action: use coldheart
  - name: wrydame
    kind: tool
    category: reporting
    desc: Reporting framework
    tags:
      - reporting
      - report
    action: use wrydame
