default_dirs:
 .:
  - ch.py
  - config.yaml

 exploits:
  doublepulsar:
   - adfw-2.dll
   - adfw.dll
   - cnli-0.dll
   - cnli-1.dll
   - coli-0.dll
   - crli-0.dll
   - dmgd-1.dll
   - dmgd-4.dll
   - esco-0.dll
   - exma-1.dll
   - exma.dll
   - iconv.dll
   - libcurl.dll
   - libeay32.dll
   - libiconv-2.dll
   - libxml2.dll
   - pcla-0.dll
   - pcre-0.dll
   - pcrecpp-0.dll
   - pcreposix-0.dll
   - posh-0.dll
   - posh.dll
   - pytrch.py
   - pytrch.pyc
   - riar-2.dll
   - riar.dll
   - ssleay32.dll
   - tibe-1.dll
   - tibe-2.dll
   - tibe.dll
   - trch-0.dll
   - trch-1.dll
   - trch.dll
   - trfo-0.dll
   - trfo-2.dll
   - trfo.dll
   - tucl-1.dll
   - tucl.dll
   - ucl.dll
   - xdvl-0.dll
   - zibe.dll
   - zlib1.dll
   - _pytrch.pyd
   - Doublepulsar-1.3.1.exe
   - Doublepulsar-1.3.1.0.xml

  eternalblue:
   - adfw-2.dll
   - adfw.dll
   - cnli-0.dll
   - cnli-1.dll
   - coli-0.dll
   - crli-0.dll
   - dmgd-1.dll
   - dmgd-4.dll
   - esco-0.dll
   - exma-1.dll
   - exma.dll
   - iconv.dll
   - libcurl.dll
   - libeay32.dll
   - libiconv-2.dll
   - libxml2.dll
   - pcla-0.dll
   - pcre-0.dll
   - pcrecpp-0.dll
   - pcreposix-0.dll
   - posh-0.dll
   - posh.dll
   - pytrch.py
   - pytrch.pyc
   - riar-2.dll
   - riar.dll
   - ssleay32.dll
   - tibe-1.dll
   - tibe-2.dll
   - tibe.dll
   - trch-0.dll
   - trch-1.dll
   - trch.dll
   - trfo-0.dll
   - trfo-2.dll
   - trfo.dll
   - tucl-1.dll
   - tucl.dll
   - ucl.dll
   - xdvl-0.dll
   - zibe.dll
   - zlib1.dll
   - _pytrch.pyd
   - Eternalblue-2.2.0.exe
   - Eternalblue-2.2.0.0.xml

 imports:
   - __init__.py
   - banners.py
   - op_setup.py
   - paths.py
   - styles.py

 touches:
   architouch:
    - adfw-2.dll
    - adfw.dll
    - Architouch-1.0.0.0.xml
    - Architouch-1.0.0.exe
    - cnli-0.dll
    - cnli-1.dll
    - coli-0.dll
    - crli-0.dll
    - dmgd-1.dll
    - dmgd-4.dll
    - esco-0.dll
    - exma-1.dll
    - exma.dll
    - iconv.dll
    - libcurl.dll
    - libeay32.dll
    - libiconv-2.dll
    - libxml2.dll
    - pcla-0.dll
    - pcre-0.dll
    - pcrecpp-0.dll
    - pcreposix-0.dll
    - posh-0.dll
    - posh.dll
    - pytrch.py
    - pytrch.pyc
    - riar-2.dll
    - riar.dll
    - ssleay32.dll
    - tibe-1.dll
    - tibe-2.dll
    - tibe.dll
    - trch-0.dll
    - trch-1.dll
    - trch.dll
    - trfo-0.dll
    - trfo-2.dll
    - trfo.dll
    - tucl-1.dll
    - tucl.dll
    - ucl.dll
    - xdvl-0.dll
    - zibe.dll
    - zlib1.dll
    - _pytrch.pyd

   namedpipetouch:
    - adfw-2.dll
    - adfw.dll
    - cnli-0.dll
    - cnli-1.dll
    - coli-0.dll
    - crli-0.dll
    - dmgd-1.dll
    - dmgd-4.dll
    - esco-0.dll
    - exma-1.dll
    - exma.dll
    - iconv.dll
    - libcurl.dll
    - libeay32.dll
    - libiconv-2.dll
    - libxml2.dll
    - Namedpipetouch-2.0.0.0.xml
    - Namedpipetouch-2.0.0.exe
    - pcla-0.dll
    - pcre-0.dll
    - pcrecpp-0.dll
    - pcreposix-0.dll
    - posh-0.dll
    - posh.dll
    - pytrch.py
    - pytrch.pyc
    - riar-2.dll
    - riar.dll
    - ssleay32.dll
    - tibe-1.dll
    - tibe-2.dll
    - tibe.dll
    - trch-0.dll
    - trch-1.dll
    - trch.dll
    - trfo-0.dll
    - trfo-2.dll
    - trfo.dll
    - tucl-1.dll
    - tucl.dll
    - ucl.dll
    - xdvl-0.dll
    - zibe.dll
    - zlib1.dll
    - _pytrch.pyd

   rpctouch:
    - adfw-2.dll
    - adfw.dll
    - cnli-0.dll
    - cnli-1.dll
    - coli-0.dll
    - crli-0.dll
    - dmgd-1.dll
    - dmgd-4.dll
    - esco-0.dll
    - exma-1.dll
    - exma.dll
    - iconv.dll
    - libcurl.dll
    - libeay32.dll
    - libiconv-2.dll
    - libxml2.dll
    - pcla-0.dll
    - pcre-0.dll
    - pcrecpp-0.dll
    - pcreposix-0.dll
    - posh-0.dll
    - posh.dll
    - pytrch.py
    - pytrch.pyc
    - riar-2.dll
    - riar.dll
    - Rpctouch-2.1.0.0.xml
    - Rpctouch-2.1.0.exe
    - ssleay32.dll
    - tibe-1.dll
    - tibe-2.dll
    - tibe.dll
    - trch-0.dll
    - trch-1.dll
    - trch.dll
    - trfo-0.dll
    - trfo-2.dll
    - trfo.dll
    - tucl-1.dll
    - tucl.dll
    - ucl.dll
    - xdvl-0.dll
    - zibe.dll
    - zlib1.dll
    - _pytrch.pyd

   smbtouch:
    - adfw-2.dll
    - adfw.dll
    - cnli-0.dll
    - cnli-1.dll
    - coli-0.dll
    - crli-0.dll
    - dmgd-1.dll
    - dmgd-4.dll
    - esco-0.dll
    - exma-1.dll
    - exma.dll
    - iconv.dll
    - libcurl.dll
    - libeay32.dll
    - libiconv-2.dll
    - libxml2.dll
    - pcla-0.dll
    - pcre-0.dll
    - pcrecpp-0.dll
    - pcreposix-0.dll
    - posh-0.dll
    - posh.dll
    - pytrch.py
    - pytrch.pyc
    - riar-2.dll
    - riar.dll
    - Smbtouch-1.1.1.0.xml
    - Smbtouch-1.1.1.exe
    - ssleay32.dll
    - tibe-1.dll
    - tibe-2.dll
    - tibe.dll
    - trch-0.dll
    - trch-1.dll
    - trch.dll
    - trfo-0.dll
    - trfo-2.dll
    - trfo.dll
    - tucl-1.dll
    - tucl.dll
    - ucl.dll
    - xdvl-0.dll
    - zibe.dll
    - zlib1.dll
    - _pytrch.pyd

description: "Windows SMB Exploitation Techniques"
name: ColdHeart
version: 3.0
